[versions]
appcompat = "1.6.1"
cardview = "1.0.0"
constraintlayout = "2.1.4"
core = "1.10.3"
coreKtx = "1.13.0"
coreKtxVersion = "1.8.1"
coreSplashscreen = "1.0.1"
devtoolsKsp = "1.9.23-1.0.20"
espressoCore = "3.5.1"
firebaseAnalyticsKtx = "21.6.2"
firebaseBom = "32.8.1"
firebaseConfigKtx = "21.6.3"
firebaseCrashlyticsGradle = "2.9.9"
firebaseCrashlyticsKtx = "19.0.3"
firebaseMessagingKtx = "23.4.1"
fragmentKtx = "1.6.2"
googleServices = "4.4.1"
gradle = "8.3.2"
hiltAndroid = "2.51.1"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlinGradlePlugin = "1.9.23"
kotlinStdlibJdk7 = "1.9.23"
kotlinxCoroutinesAndroid = "1.8.0"
legacySupportV4 = "1.0.0"
lifecycleCommonJava8 = "2.7.0"
material = "1.11.0"
materialTapTargetPrompt = "3.3.2"
mockitoAndroid = "5.11.0"
mockitoCore = "5.11.0"
navigationFragmentKtx = "2.7.7"
orchestrator = "1.4.2"
ossLicensesPlugin = "0.10.6"
paletteKtx = "1.0.0"
playServicesOssLicenses = "17.0.1"
preferenceKtx = "1.2.1"
recyclerview = "1.3.2"
review = "2.0.1"
roomRuntime = "2.6.1"
runner = "1.5.2"
spotless = "6.25.0"
truth = "1.5.0"
truthVersion = "1.4.2"
ucrop = "2.2.8"
viewpager2 = "1.0.0"
workTesting = "2.9.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleCommonJava8" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleCommonJava8" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleCommonJava8" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycleCommonJava8" }
androidx-navigation-dynamic-features-fragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigationFragmentKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-orchestrator = { module = "androidx.test:orchestrator", version.ref = "orchestrator" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomRuntime" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-truth = { module = "androidx.test.ext:truth", version.ref = "truth" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workTesting" }
core = { module = "com.google.android.play:core", version.ref = "core" }
core-ktx = { module = "com.google.android.play:core-ktx", version.ref = "coreKtxVersion" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebaseAnalyticsKtx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-config = { module = "com.google.firebase:firebase-config", version.ref = "firebaseConfigKtx" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlyticsKtx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessagingKtx" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroid" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlinStdlibJdk7" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-tap-target-prompt = { module = "uk.co.samuelwall:material-tap-target-prompt", version.ref = "materialTapTargetPrompt" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoAndroid" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
oss-licenses-plugin = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "ossLicensesPlugin" }
play-services-oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "playServicesOssLicenses" }
review = { module = "com.google.android.play:review", version.ref = "review" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review" }
truth = { module = "com.google.truth:truth", version.ref = "truthVersion" }
truth-java8-extension = { module = "com.google.truth.extensions:truth-java8-extension", version.ref = "truthVersion" }
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }

[plugins]
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid"}
diffplug-spotless = { id = "com.diffplug.spotless", version.ref = "spotless"}
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtoolsKsp" }
